windowrule = float 1, match:class ^(Viewnior)$
windowrule = float 1, match:class ^(imv)$
windowrule = float 1, match:class ^(mpv)$
windowrule = pin 1, match:class ^(rofi)$
windowrule = pin 1, match:class ^(waypaper)$
windowrule = float 1, match:title ^(Transmission)$
windowrule = float 1, match:title ^(Volume Control)$
windowrule = float 1, match:title ^(Firefox — Sharing Indicator)$
windowrule = move 0 0, match:title ^(Firefox — Sharing Indicator)$
windowrule = size 700 450, match:title ^(Volume Control)$
windowrule = move 40 55%, match:title ^(Volume Control)$
windowrule = float 1, match:title ^(Picture-in-Picture)$
windowrule = opacity 1.0 override 1.0 override, match:title ^(Picture-in-Picture)$
windowrule = pin 1, match:title ^(Picture-in-Picture)$
windowrule = opacity 1.0 override 1.0 override, match:title ^(.*imv.*)$
windowrule = opacity 1.0 override 1.0 override, match:title ^(.*mpv.*)$
windowrule = opacity 1.0 override 1.0 override, match:class (Unity)
windowrule = opacity 1.0 override 1.0 override, match:class (firefox)
windowrule = opacity 1.0 override 1.0 override, match:class (evince)
windowrule = workspace 3, match:class ^(evince)$
windowrule = workspace 4, match:class ^(Gimp-2.10)$
windowrule = workspace 5, match:class ^(Spotify)$
windowrule = workspace 8, match:class ^(com.obsproject.Studio)$
windowrule = workspace 10, match:class ^(discord)$
windowrule = workspace 10, match:class ^(WebCord)$
windowrule = float 1, match:class ^(org.gnome.Calculator)$
windowrule = float 1, match:class ^(waypaper)$
windowrule = float 1, match:class ^(zenity)$
windowrule = size 850 500, match:class ^(zenity)$
windowrule = float 1, match:class ^(org.gnome.FileRoller)$
windowrule = float 1, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float 1, match:class ^(.sameboy-wrapped)$
windowrule = float 1, match:class ^(file_progress)$
windowrule = float 1, match:class ^(confirm)$
windowrule = float 1, match:class ^(dialog)$
windowrule = float 1, match:class ^(download)$
windowrule = float 1, match:class ^(notification)$
windowrule = float 1, match:class ^(error)$
windowrule = float 1, match:class ^(confirmreset)$
windowrule = float 1, match:title ^(Open File)$
windowrule = float 1, match:title ^(File Upload)$
windowrule = float 1, match:title ^(branchdialog)$
windowrule = float 1, match:title ^(Confirm to replace files)$
windowrule = float 1, match:title ^(File Operation Progress)$
windowrule = opacity 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = no_anim on, match:class ^(xwaylandvideobridge)$
windowrule = no_initial_focus on, match:class ^(xwaylandvideobridge)$
windowrule = max_size 1 1, match:class ^(xwaylandvideobridge)$
windowrule = no_blur on, match:class ^(xwaylandvideobridge)$
windowrule = border_size 0, match:float 0, match:workspace w[t1]
windowrule = rounding 0, match:float 0, match:workspace w[t1]
windowrule = border_size 0, match:float 0, match:workspace w[tg1]
windowrule = rounding 0, match:float 0, match:workspace w[tg1]
windowrule = opaque on, match:class ^()$, match:title ^()$
windowrule = no_shadow on, match:class ^()$, match:title ^()$
windowrule = no_blur on, match:class ^()$, match:title ^()$
windowrule = suppress_event activate, match:class ^(telegram-desktop)$
windowrule = no_focus on, match:class ^(telegram-desktop)$

workspace = w[t1], gapsout:4 8 8 8, gapsin:4
workspace = w[tg1], gapsout:4 8 8 8, gapsin:4
workspace = f[1], gapsout:4 8 8 8, gapsin:4
