# Startup (classic Waybar / SwayNC / hypridle)

exec-once = dbus-update-activation-environment --all --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = hyprlock

exec-once = nm-applet &
exec-once = poweralertd &
exec-once = wl-clip-persist --clipboard both &
exec-once = wl-paste --watch cliphist store &
exec-once = udiskie --automount --notify --smart-tray &
exec-once = hyprctl setcursor Bibata-Modern-Ice 24 &
exec-once = init-wallpaper &

exec-once = LANG=en_US.UTF-8 waybar &
exec-once = swaync &
exec-once = hypridle &
