# Enable True color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -gq allow-passthrough on

set -g base-index 1
set -g pane-base-index 1

set-option -g prefix C-b
set-option -g prefix2 none

set -g detach-on-destroy off

# Utility bindings
unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind %
bind h split-window -h -c "#{pane_current_path}"

unbind '"'
bind v split-window -v -c "#{pane_current_path}"

# resizing panes with Alt+hjkl
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5
bind -r M-h resize-pane -L 5

# maximize panes
bind -r m resize-pane -Z

# disable kill accept prompt
bind-key x kill-pane

# mouse support
set -g mouse on

# vim shell navigations and selects in tmux panes
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Sesh keybinds
bind-key "K" display-popup -E -w 40% "sesh connect \"$(
    sesh list -i | gum filter --no-strip-ansi --limit 1 --placeholder 'Pick session' --prompt='🛸 '
)\""

bind-key "T" run-shell "sesh connect \"$(
        sesh list --icons | fzf-tmux -p 90%,80% \
        --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
        --header '🔑 ^a all | ^t tmux | ^g conf | ^x zoxide | ^d tmux kill | ^f find' \
        --bind 'tab:down,btab:up' \
        --bind 'ctrl-a:change-prompt(🛸  )+reload(sesh list --icons)' \
        --bind 'ctrl-t:change-prompt(◧  )+reload(sesh list -t --icons)' \
        --bind 'ctrl-g:change-prompt(⛯  )+reload(sesh list -c --icons)' \
        --bind 'ctrl-x:change-prompt(🗃  )+reload(sesh list -z --icons)' \
        --bind 'ctrl-f:change-prompt(🔭  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
        --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(👽  )+reload(sesh list --icons)' \
        --preview-window 'right:55%' \
        --preview 'sesh preview {}'
)\""

# tmux goodies
bind-key -r f run-shell "tmux neww ~/scripts/tmux-sessionizer.sh"
bind-key n command-prompt "new-session -s '%%'"

# Drag copy using mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# tmux plugin manager
set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/.tmux/plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin 'catppuccin/tmux'

set -g @sessionx-bind 'o'
set -g @resurrect-capture-pane-contents "on"

# Configure Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"


# status left look and feel
set -g status-left-length 100
set -g status-left "#[bg=#1e1e2e,fg=#a6e3a1]  #S "
set -ga status-left "#[bg=#1e1e2e,fg=#6c7086]│#[bg=#1e1e2e,fg=#89b4fa]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# Configure Tmux
set -g status-position bottom
set -g status-style "bg=#1e1e2e"
set -g status-justify "absolute-centre"

# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

set -g window-status-format " #I#W "
set -g window-status-style "bg=#1e1e2e,fg=#6c7086"
set -g window-status-activity-style "bg=#1e1e2e,fg=#f38ba8"
set -g window-status-bell-style "bg=#1e1e2e,fg=#f38ba8,bold"
set -gF window-status-separator "#[bg=#1e1e2e,fg=#6c7086]│"

set -g window-status-current-format " #I#W "
set -g window-status-current-style "bg=#89b4fa,fg=#1e1e2e,bold"

run '~/.config/tmux/.tmux/plugins/tpm/tpm'
